"""
******************************************************************************
*  Copyright 2023 Labforge Inc.                                              *
*                                                                            *
* Licensed under the Apache License, Version 2.0 (the "License")            *
* you may not use this project except in compliance with the License.        *
* You may obtain a copy of the License at                                    *
*                                                                            *
*     http://www.apache.org/licenses/LICENSE-2.0                             *
*                                                                            *
* Unless required by applicable law or agreed to in writing, software        *
* distributed under the License is distributed on an "AS IS" BASIS,          *
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
* See the License for the specific language governing permissions and        *
* limitations under the License.                                             *
******************************************************************************

Configuration generator from Bottlenose Persistence File. Use this to update
the declared parameters of the ros2 driver for different firmware versions.

"""
__author__ = "Thomas Reidemeister <thomas@labforge.ca>"
__copyright__ = "Copyright 2023, Labforge Inc."

import sys
from os.path import basename
import xml.etree.ElementTree as ET

TEMPLATE = """/******************************************************************************
 *  Copyright 2023 Labforge Inc.                                              *
 *                                                                            *
 * Licensed under the Apache License, Version 2.0 (the "License");            *
 * you may not use this project except in compliance with the License.        *
 * You may obtain a copy of the License at                                    *
 *                                                                            *
 *     http://www.apache.org/licenses/LICENSE-2.0                             *
 *                                                                            *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 ******************************************************************************
@file {filename} {description}

This file is autogenerated, do not edit.
*/
#ifndef __parameter_definitions__
#define __parameter_definitions__

const char *parameter_list[] = {parameters};
#endif // __parameter_definitions__
"""


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: parameter_gen.py <input_file> <output_file>', file=sys.stderr)
        sys.exit(1)

    infile = sys.argv[1]
    outfile = sys.argv[2]

    tree = ET.parse(infile)
    root = tree.getroot()

    parameters = []

    for child in  root.find('device').find('device').iter():
        if 'name' in child.attrib:
            # Skip system parameters
            if child.attrib['name'].find('[') >= 0:
                continue
            if child.attrib['name'].find('Gev') == 0:
                continue
            #print(child.attrib['name'], child.text)
            parameters.append('"'+child.attrib['name']+'",')
    out = '{\n'+ '\n    '.join(parameters) + '\n}'
    with open(outfile, 'w') as f:
        f.write(TEMPLATE.format(filename=basename(outfile), description='Parameter definitions', parameters=out))
